name: Setup Rust Environment
description: Setup Rust toolchain with WASM target and wasm-pack

runs:
  using: composite
  steps:
    - name: Setup C++
      run: |
        sudo apt-get update
        sudo apt-get install libstdc++-12-dev
      shell: bash

    - name: Setup Rust
      uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5 # v1.2.0
      with:
        targets: wasm32-unknown-unknown
        channel: nightly
        components: clippy,rustfmt
        target-dirs: web-csv-toolbox-wasm/target

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      shell: bash
