packages:
  - packages/*
  - docs

catalog:
  typescript: ~5.4.5
  vite: ^5.4.2
  vite-plugin-dts: ^4.0.3
  vite-plugin-wasm: ^3.3.0
  '@codecov/vite-plugin': ^1.0.1
  '@rollup/pluginutils': ^5.1.0
  '@types/node': ^20.16.5
