name: CD

on:
  # Run this workflow when a workflow_run event is triggered
  # from the "Node.js CI" workflows
  # and the workflow_run's status is "completed"
  # and the workflow_run's base branch is "main".
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # Build the package and upload it as an artifact
  build:
    name: Build
    uses: ./.github/workflows/.build.yaml
  # Release the package to npm
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    # Only run this job if the workflow_run's conclusion was "success"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write # Used to commit to "Version Packages" PR
      pull-requests: write # Used to create "Version Packages" PR
      id-token: write # Used to publish to npm with provenance statements
      # Other permissions are defaulted to none
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 8
      - name: Setup Node.js 20
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23 # v1.4.5
        with:
          publish: pnpm exec changeset publish
          version: pnpm exec changeset version
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      published: ${{ steps.changesets.outputs.published }}

  # If the release job not published, run this job to publish a prerelease
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: release
    if: needs.release.outputs.published == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      - name: Creating .npmrc
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "Release @next"
        run: |
          pnpm exec changeset version --snapshot next
          pnpm exec changeset publish --no-git-tag --snapshot --tag next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This job is used to deploy the documentation to GitHub Pages
  doc:
    runs-on: ubuntu-latest
    # if the release job was successful, run this job
    needs:
      - build
      - release
    if: needs.release.outputs.published == 'true'
    concurrency:
      group: GitHub Pages
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 8
      - name: Setup Node.js 20
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      - name: Build
        run: pnpm build:js
      - name: Build documentation
        run: pnpm run doc
      - name: Configure GitHub Pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: doc
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@87c3283f01cd6fe19a0ab93a23b2f6fcba5a8e42 # v4.0.3
